name: AI Suite AutoTest

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4:00 UTC
  workflow_dispatch:

jobs:
  full-redteam-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install openai requests pyyaml anthropic

      - name: Run Wild Exploit Ingest
        run: python wild_exploit_ingest.py || true

      - name: Run Polyglot Smoke Tests
        run: python polyglot_chains/polyglot_smoke_test.py || true

      - name: Run Fuzzer
        run: |
          cd fuzzer
          python prompt_fuzzer.py

      - name: Run Agent Swarm
        run: |
          cd agent_worms
          python multiapi_swarm_runner.py

      - name: Upload Logs/Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ai-suite-logs
          path: |
            staging/fuzz_logs/
            staging/
            agent_worms/
